solucion/Models/Control.cs
namespace solucion.Models
{
    public class Control
    {
        public int Id { get; set;}
        public DateTime? Income { get; set;}
        public DateTime? Output { get; set;}
        public int? EmployeesId { get; set; }

    }

}

solucion/Models/Employee.cs
namespace solucion.Models
{
    public class Employee{
        public int Id { get; set; }
        public string? Names { get; set; }
        public string? LastNames { get; set; }
        public string? Email { get; set; }
        public string? PhotoProfile { get; set; }
        public string? Password { get; set; }

    }
    
}

solucion/Models/ErrorViewModel.cs
namespace solucion.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

solucion/Controllers/ControlsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using solucion.Data;
using solucion.Models;

namespace solucion.Controllers
{
    public class ControlsController : Controller
    {
        private readonly RegistroContext _context;

        public ControlsController(RegistroContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Income()
        {
            var id = HttpContext.Session.GetInt32("Id");
            return Json(id);
            var lista = new Control(){
                Income = DateTime.Now,
                EmployeesId = id
            };
           _context.Controls.Add(lista);
           await _context.SaveChangesAsync();
           return RedirectToAction("Index", "Employees");            
        }
    }
}

solucion/Controllers/EmployeesController.cs
using Microsoft.AspNetCore.Mvc;
using solucion.Models;
using solucion.Data;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;

namespace solucion.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly RegistroContext _context;

        public EmployeesController(RegistroContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {           

            ViewBag.Nombre = HttpContext.Session.GetString("Names");
            ViewBag.LastNames = HttpContext.Session.GetString("LastNames");
            ViewBag.PhotoProfile = HttpContext.Session.GetString("PhotoProfile");
            ViewBag.Email = HttpContext.Session.GetString("Email");

            if(ViewBag.Nombre != null){
                return View(_context.Controls.ToList());

            }else{
                return RedirectToAction("Index", "Home");
            }
            
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Create()
        {
            return View();
        }





    }
}

solucion/Controllers/HomeController.cs
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.EntityFrameworkCore.Storage;
using solucion.Data;
using solucion.Models;
using Microsoft.EntityFrameworkCore;

namespace solucion.Controllers;

public class HomeController : Controller
{
    private readonly RegistroContext _context;

    public HomeController(RegistroContext context)
    {
        _context = context;
    }

    public IActionResult Index(string message = "")
    {
        ViewBag.Message = message;
  
        return View();
    }


    [HttpPost]
    public async Task<IActionResult> Login(string email, string password)
    {
        if(!string.IsNullOrEmpty(email))
        {
            //Hacemos uso de la base de datos
            var user = await _context.Employees.FirstOrDefaultAsync(r => r.Email == email);

            if(user != null && user.Password == password ) //Si el usuario es diferente de null
            {
                HttpContext.Session.SetString("Names", user.Names);
                HttpContext.Session.SetInt32("Id", user.Id);
                HttpContext.Session.SetString("LastNames", user.LastNames);
                HttpContext.Session.SetString("PhotoProfile", user.PhotoProfile);
                HttpContext.Session.SetString("Email", user.Email);
                //Encontramos un usuario con los datos
                return RedirectToAction("Index", "Employees");
            }
            else if(user != null && user.Password != password ) 
            {
                return RedirectToAction("Index", new {message = "Incorrect user or password"});  
            }
            else
            {
                return RedirectToAction("Index" , new {message = "User not registered"} ) ;                
            }

        }
        else
        {
            return RedirectToAction("Index", new {message = "Fill in the fields to be able to login"});
        }
    }
    

}

solucion/Views/Employees/Create.cshtml
@{
    ViewData["Title"] = "Create Page";
    <link rel="stylesheet" href="~/css/employees.css" asp-append-version="true" />
}

@model Employee

<header >
    <nav id="header" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand col-6 ms-2" asp-area="" asp-controller="Employees" asp-action="Index">
                <img src="~/img/cyd.png" style="width: 90px; ;">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between col-">
                <ul class="navbar-nav flex-grow-1 dropdown d-flex justify-content-end align-items-center">
                    <li class="nav-item">
                        <p style="font-size: 12px;" class="align-items-cente"><b>Welcome @ViewBag.Nombre @ViewBag.LastNames</b></p>
                    </li>
                    <li class="nav-item">
                        <img src="@ViewBag.PhotoProfile" style="width:50px; border-radius:50px " class="ms-2 nav-link">
                    </li>
                    <div class="dropdown-menu" id="menu">
                        <a class="dropdown-item" href="#">History</a>
                        <a class="dropdown-item" asp-controller="Employees" asp-action="Create">Add employee</a>
                        <form asp-controller="Employees" asp-action="Logout" method="post">
                            <button class="dropdown-item" type="submit">Sign Out</button>
                        </form>
                    </div>
                </ul>
            </div>
        </div>  
    </nav>
</header>

<div class="container">
    <div class="row justify-content-center align-items-center " style="height: 100vh;">
        <div class="card col-md-5 shadow">
            <div class="text-center">
                <img class="m-3" src="~/img/cyd.png" style="width: 200px;">
            </div>
            <form asp-action="Create" method="post">
                <div class="mb-3">
                    <label for="Photo" class="form-label"><b>PhotoProfile:</b></label>
                    <input type="file" id="foto" class="form-control">
                </div>
                <div class="form-group">
                    <label asp-for="Names"><b>Names:</b></label>
                    <input asp-for="Names" class="form-control" />
                    <span asp-validation-for="Names" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LastNames"><b>LastNames:</b></label>
                    <input asp-for="LastNames" class="form-control" />
                    <span asp-validation-for="LastNames" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email"><b>Email:</b></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Password"><b>Password:</b></label>
                    <input asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="text-center" >
                    <button class="btn btn-outline-dark shadow mt-4 m-3 w-50" >CREAR</button>
                </div>
            </form>
        </div>
    </div> 
</div>

<div class="container col-4">
    <div class="text-center">
        <img class="m-3" src="~/img/cyd.png" style="width: 200px;">
    </div>
    <form asp-action="Create" method="post">
        <div class="mb-3">
            <label for="Photo" class="form-label"><b>PhotoProfile:</b></label>
            <input type="file" id="foto" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="Names"><b>Names:</b></label>
            <input asp-for="Names" class="form-control" />
            <span asp-validation-for="Names" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="LastNames"><b>LastNames:</b></label>
            <input asp-for="LastNames" class="form-control" />
            <span asp-validation-for="LastNames" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Email"><b>Email:</b></label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Password"><b>Password:</b></label>
            <input asp-for="Password" class="form-control" />
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>
        <div>
            <button type="submit" class="btn btn-outline-black mt-3 text-center">CREAR</button>
        </div>
    </form> 
</div>

<footer class="border-top footer text-muted fixed-bottom" id="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-6 text-start">
                &copy; 2024 - Work Entry and Exit System <a href="https://github.com/CristhianDavid0207/Registro-Entrada-y-Salida">Daniel Toro | Cristhian Bermudez</a>
            </div>
            <div class="col-6 text-end">
                <marquee><p><b>Welcome to our spectacular page</b></p></marquee>
            </div>
        </div>
    </div>
</footer>

solucion/Views/Employees/Index.cshtml
@{
    <link rel="stylesheet" href="~/css/employees.css" asp-append-version="true" />
}
<header >
    <nav id="header" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand col-6 ms-2" asp-area="" asp-controller="Employees" asp-action="Index">
                <img src="~/img/cyd.png" style="width: 90px; ;">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between col-">
                <ul class="navbar-nav flex-grow-1 dropdown d-flex justify-content-end align-items-center">
                    <li class="nav-item">
                        <p style="font-size: 12px;" class="align-items-cente"><b>Welcome @ViewBag.Nombre @ViewBag.LastNames</b></p>
                    </li>
                    <li class="nav-item">
                        <img src="@ViewBag.PhotoProfile" style="width:50px; border-radius:50px " class="ms-2 nav-link">
                    </li>
                    <div class="dropdown-menu" id="menu">
                        <a class="dropdown-item" href="#">History</a>
                        <a class="dropdown-item" asp-controller="Employees" asp-action="Create">Add employee</a>
                        <form asp-controller="Employees" asp-action="Logout" method="post">
                            <button class="dropdown-item" type="submit">Sign Out</button>
                        </form>
                    </div>
                </ul>
            </div>
        </div>  
    </nav>
</header>

<div class="container " style="height: 80vh;">
    <div class="row d-flex justify-content-center align-items-center">  
        <div class="card border-0 align-items-center col-6" style="background-color: rgb(190, 190, 190);">
            <img src="@ViewBag.PhotoProfile" style="width: 100px; border-radius:50px " class="m-3 text-center  ">
            <h2 class="text-center mb-0">@ViewBag.Nombre @ViewBag.LastNames</h2> 
            <p>@ViewBag.Email</p>
            <div class=" d-column justify-content-center text-center">
                <form asp-controller="Controls" asp-action="Income" method="post">
                    <button class="button1 m-3" type="submit">Register Entry</button>
                </form>
                <a class="button2 m-3">Register Departure</a>
            </div>
        </div>      
    </div>
</div>


<footer class="border-top footer text-muted fixed-bottom" id="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-6 text-start">
                &copy; 2024 - Work Entry and Exit System <a href="https://github.com/CristhianDavid0207/Registro-Entrada-y-Salida">Daniel Toro | Cristhian Bermudez</a>
            </div>
            <div class="col-6 text-end">
                <marquee><p><b>Welcome to our spectacular page</b></p></marquee>
            </div>
        </div>
    </div>
</footer>

        

solucion/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home | LogIn";
    <link rel="stylesheet" href="~/css/employees.css" asp-append-version="true" />
}

@model Employee

<header >
    <nav id="header" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand col-6 ms-2">
                <img src="~/img/cyd.png" style="width: 90px; ;">
            </a>
        </div>  
    </nav>
</header>
<div class="container">
    <div class="row justify-content-center align-items-center " style="height: 100vh;">
        <div class="card col-md-5 shadow">
            <div class="text-center">
                <img class="m-3" src="~/img/cyd.png" style="width: 200px;">
            </div>
            @{
                if(!string.IsNullOrEmpty(ViewBag.Message))
                {
                    //Mensaje tiene valor
                    <div class="alert alert-danger m-2">@ViewBag.Message</div>
                }
            }
            <form asp-controller="Home" asp-action="Login" method="post">
                <div class="form-group m-3">
                    <label asp-for="Email"></label>
                    <input class="form-control shadow" name="email" asp-for="Email">
                </div>
                <div class="form-group m-3">
                    <label asp-for="Password"></label>
                    <input class="form-control shadow" type="password" name="password" asp-for="Password">
                </div>
                <div class="text-center" >
                    <button class="btn btn-outline-dark shadow mt-0 m-3 w-50" >Login</button>
                </div>
            </form>
        </div>            
    </div>
</div>

<footer class="border-top footer text-muted fixed-bottom" id="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-6 text-start">
                &copy; 2024 - Sistema de Ingresos y Salidas Laborales <a href="https://github.com/CristhianDavid0207/Registro-Entrada-y-Salida">Daniel Toro | Cristhian Bermudez</a>
            </div>
            <div class="col-6 text-end">
                <marquee><p><b>Animo....ya casi ingresas a nuestra pagina</b></p></marquee>
            </div>
        </div>
    </div>
</footer>

solucion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/solucion.styles.css" asp-append-version="true" />
</head>
<body>

    <div >
        <main role="main" class="">
            @RenderBody()   
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>